<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5xou3lq\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5xou3lq/appProdProjectContainer.php') {
    touch(__DIR__.'/Container5xou3lq.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container5xou3lq\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container5xou3lq\appProdProjectContainer([
    'container.build_hash' => '5xou3lq',
    'container.build_id' => 'b729d886',
    'container.build_time' => 1619524123,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5xou3lq');
